
###

GET http://localhost:3333/pontoDeColeta


###

POST http://localhost:3333/pontoDeColeta
Content-Type: application/json

{
    "name": "praia lalalal",
    "endereco": "rua sao jorge ",
    "complemento": "casa 02",
    "descricao": "o kok o ko ko k o"

    
}

###

PUT http://localhost:3333/pontoDeColeta/ae14c592-c367-48d1-8e24-7f808b058c88
Content-Type: application/json

{ 
    "name": "dsad ladsadalalal",
    "endereco": "weweee ",
    "complemento": "gggggg",
    "descricao": "wwwww"
}

###

DELETE http://localhost:3333/pontoDeColeta
